---
name: autopkg

on:
  push:
    paths:
      - "**autopkg.yaml"

jobs:
  autopkg:
    # based upon: https://github.com/jgstew/jgstew-recipes/blob/main/Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: git clone autopkg
        run: git clone https://github.com/jgstew/autopkg.git
      - name: switch autopkg branch
        run: cd autopkg && git checkout dev
      - name: install requirements autopkg
        run: cd autopkg && pip3 install --requirement requirements.txt --quiet
      - name: create autopkg config dir
        run: pwd && cd ~ && mkdir -p .config/Autopkg
      - name: create default autopkg config files
        run: cd ~ && echo {} > .config/Autopkg/config.json
      - name: add autopkg repos
        run: for line in $(cat .autopkg_repos.txt); do python3 autopkg/Code/autopkg repo-add $line; done
      - name: run autopkg info
        run: python3 autopkg/Code/autopkg info
      - name: install requirements jgstew recipes
        run: cd autopkg && pip3 install --requirement /home/runner/Library/AutoPkg/RecipeRepos/com.github.jgstew.jgstew-recipes/requirements.txt --quiet
      - name: run autopkg recipe
        run: cd /home/runner/Library/AutoPkg/RecipeRepos/com.github.jgstew.jgstew-recipes && python3 /home/runner/work/bigfix-content/bigfix-content/autopkg/Code/autopkg run -v com.github.jgstew.bigfix.log4j2-scan-Win64
      - name: copy generated file
        run: cp "/home/runner/Library/AutoPkg/Cache/com.github.jgstew.bigfix.log4j2-scan-Win64/Logpresso log4j2-scan - Windows x64 - Remediate.bes" "fixlet/Logpresso log4j2-scan - Windows x64 - Remediate.bes"
      # https://lannonbr.com/blog/2019-12-09-git-commit-in-actions
      - name: setup git config
        run: |
          # setup the username and email.
          git config user.name "GitHub Actions Runner"
          git config user.email "<>"
      # - name: commit
      #   run: |
      #     # Stage the file, commit and push
      #     git add "fixlet/Logpresso log4j2-scan - Windows x64 - Remediate.bes"
      #     git commit -m "new logpresso"
      #     git push
