---
name: ParseRelaysDotDat

on:
  push:
    paths:
      - ".github/workflows/ParseRelaysDotDat.yaml"
  pull_request:
    paths:
      - "**Relays.dat"
      # - ".github/workflows/ParseRelaysDotDat.yaml"

jobs:
  ParseRelaysDotDat:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      # https://stackoverflow.com/a/74268200/861745
      - name: Get changed files
        id: changed-files
        shell: bash
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | grep 'Relays.dat$' | xargs)" >> $GITHUB_OUTPUT
          else
            echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'Relays.dat$' | xargs)" >> $GITHUB_OUTPUT
          fi

      - name: List changed files
        shell: bash
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
            echo "$file was changed"
          done

      # - name: Download ParseRelaysDotDat.exe
      #   shell: bash
      #   run: |
      #       curl -O https://bigfix-wiki.hcltechsw.com/wikis/form/anonymous/api/wiki/9800bed4-8101-452b-930b-807aed3eb996/page/e2ee048f-bc56-4798-ba0b-e57c08a23160/attachment/71245215-dbd5-4f4a-b926-14afdd9d8f3c/media/ParseRelaysDotDat.exe
      #       ls

      # - name: Run ParseRelaysDotDat
      #   run: ./ParseRelaysDotDat.exe Relays.dat
