---
name: ParseRelaysDotDatInteractive

on:
  workflow_dispatch:

jobs:
  ParseRelaysDotDatInteractive:
    runs-on: windows-latest
    steps:
      - name: Example Interactive Inputs Step
        id: interactive-inputs
        uses: boasihq/interactive-inputs@v2
        with:
          ngrok-authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          interactive: |
            - type: file
              id: uploaded_file
              name: Upload Relays.dat file
              description: 'Upload desired Relays.dat file for processing'
              required: true
              acceptedFileTypes:
                - application/octet-stream

      # http://software.bigfix.com/download/bes/util/ParseRelaysDotDat.exe
      - name: Download ParseRelaysDotDat.exe
        shell: bash
        run: |
            curl -O https://bigfix-wiki.hcltechsw.com/wikis/form/anonymous/api/wiki/9800bed4-8101-452b-930b-807aed3eb996/page/e2ee048f-bc56-4798-ba0b-e57c08a23160/attachment/71245215-dbd5-4f4a-b926-14afdd9d8f3c/media/ParseRelaysDotDat.exe
            ls

      - name: List the uploaded files in the directory
        shell: bash
        run: |
          echo "Display uploaded files"
          echo -e "\n==============================\n"
          ls -la ${{ steps.interactive-inputs.outputs.uploaded_file }} # Use the label of the multifile/file field as the key to get the uploaded file directory
          echo -e "\n==============================\n"

      - name: Run ParseRelaysDotDat
        run: ./ParseRelaysDotDat.exe ${{ steps.interactive-inputs.outputs.uploaded_file }}
